spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/memo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
  jpa:
    database: mysql
    show-sql: true
  profiles:
    active: dev, prod
server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: beans, env, health, info, conditions
